### ISSUE TITLE
bn_lstm_identity_initializer vs orthogonal_initializer discrepancy

### ISSUE THREAD

**Issue by carlthome** [OlavHN/bnlstm#6]
The input to hidden weights are initialized with one SVD meaning i, j, f, o all have orthogonal starting weights. However for the hidden to hidden weights, `bn_lstm_identity_initializer` makes three SVD function calls so it's not the case that the weights for the previous input `j`, the forget gate `f` and the output gate `o` are orthogonal. Do you think this affects learning? I would guess that it doesn't matter, but it's hard to think it through fully.

**Comment by akosiorek** [comment]
@carlthome there are only N orthogonal vectors in R^N, therefore weights for i, j, f and o cannot all be orthogonal to each other. Making one or three SVD calls does not affect this.

**Comment by carlthome** [comment]
What I'm getting at is that when you do one SVD on the large rectangular matrix, I assume that's R^{N+M} where M are some extra rows to make the rectangle square. Wouldn't we then be worried that when we split the matrix into i, j, f and o that not all of the columns in either one or all of these matrices are orthogonal with respect to each other. I get that across gates they can't be orthogonal, but that's fine.

**Comment by akosiorek** [comment]
Padding the matrix with M extra rows to make it square would have precisely the effect you're thinking about. The thing is, we don't have to pad the input matrix. You just get U \in R^{M+N}x{M} and V \in R^MxM, with rank of both equal to M. Any submatrix of U has still rank M.

**Comment by carlthome** [comment]
Aha. Cool! Thanks.
